### ISSUE TITLE
Running in terminal CLI mode?

### ISSUE THREAD

**Issue by lonnietc** [rule110-io/surge#108]
Hello,

Can Surge be run in a terminal CLI mode instead of using a browser?

Also, should I have local NKN node (nknd.exe) running so that Surge can access the network mesh, or is that built into the Surge binary?

Thanks

**Comment by MutsiMutsi** [comment]
There is currently no CLI version however it would be possible to simply build a version with just the backend code and none of the frontend code since those are entirely seperated however this would still require command line work for viewing and manipulating the application with commands. 

It is possible to run your own node and connect surge through that node, however currently it uses an algorithm to use various randomly picked nodes as its entry to the network, there is no need to run your own node and it would not benefit your surge experience.

**Comment by lonnietc** [comment]
Thanks for getting back to me on this.

I may try to investigate this since I was having real problems trying to get the "walis" build to work and wanted to just build it all natively from the command line for Go.

Maybe I can try again, and the idea would be to have it run through my local node that is always running in the background. This way, it provides as file service as well as the node get rewarded for relaying packets through the mesh.

Just a thought.
