### ISSUE TITLE
Surge 0.3.0 beta Random stuff I noticed

### ISSUE THREAD

**Issue by no112358** [rule110-io/surge#45]
1.
![surge download difference](https://user-images.githubusercontent.com/75950250/103642813-ff5b8580-4f53-11eb-8c26-fcdb0288023d.png)
I'm not sure what's causing this difference in download. Might be something weird.
2.
![surge right after removing a download job I just added](https://user-images.githubusercontent.com/75950250/103642896-1ac69080-4f54-11eb-9a23-436476a3090a.png)
I added a download and deleted it right after that and this warning showed.
3.
![surge p1](https://user-images.githubusercontent.com/75950250/103642937-2ade7000-4f54-11eb-8037-67be4d226001.png)
![surge p3](https://user-images.githubusercontent.com/75950250/103643249-a4765e00-4f54-11eb-9984-5bbbb3377d39.png)
In "file transfers", if you arrange them by file AKA filename items on page one get arranged by filename and when you switch to page 2 they get arranged by name separately and so on. All the items should be arranged by name and then presented, not just items currently on the page.

If it were up to me I'd get rid of these pages and just have one place to show all items and then just scroll up or down to see them all.
4.
![surge cpu usage](https://user-images.githubusercontent.com/75950250/103643784-86f5c400-4f55-11eb-8838-7756751f8433.png)
This laptops CPU is certainly not fast, but 10% usage seems a bit high, while Surge isn't really doing much, zero downloads/uploads. The number is 2-3% smaller if Surge is minimized. 21 items seeding.

**Comment by MutsiMutsi** [comment]
Thanks for the testing!

1. You've likely just deleted a file from surge, there will be chunks coming in up to a minute or so for chunks requests already sent, if the file is no longer present the bandwidth is only counted towards  total client bandwidth in the bottom right.
2. That is expected behaviour; the error describes the consequence of your action here
3. We will look at sorting 👍

With regards to cpu usage, the current rendering engine seems quite inefficient, there is little we can do about that right now but it should be improved a lot with wails v2 and a chromium backend (currently IE11 engine). This also ties into our paging view; performance limitations from having a web frontend.

**Comment by MutsiMutsi** [comment]
update on 1 I now see what you mean, only 1 file is showing but all three files are actually pulling bandwidth at time of that screenshot, we will investigate.

**Comment by no112358** [comment]
![surge a few secods](https://user-images.githubusercontent.com/75950250/103662357-1f993d80-4f70-11eb-9c48-6a0db4663092.png)
It can't say a few seconds under remaining if the download hasn't even started yet. Certain downloads are stuck, low on seeds, but it still says a few seconds under remaining.

![surge empty space](https://user-images.githubusercontent.com/75950250/103662616-73a42200-4f70-11eb-8154-f9cc8cec765b.png)
Now that Surge has dynamic size, the amount of items displayed should also be increased or decreased dynamically.

**Comment by MutsiMutsi** [comment]
Thanks for all these reports, I believe we have just finished every single one of these bugs reported. Coming in 0.3.1-beta.

**Comment by no112358** [comment]
> Thanks for all these reports, I believe we have just finished every single one of these bugs reported. Coming in 0.3.1-beta.

Can't wait.
