### ISSUE TITLE
cannot install on mac os big sur 11.5.2

### ISSUE THREAD

**Issue by vahidreza** [rule110-io/surge#82]
i cannot install the dmg app on mac os big sur 11.5.2

<img width="492" alt="Screen Shot 1400-11-23 at 18 23 00" src="https://user-images.githubusercontent.com/3737551/153716177-06fb7260-4625-4fe8-950e-928d8201978d.png">

<img width="251" alt="Screen Shot 1400-11-23 at 18 23 09" src="https://user-images.githubusercontent.com/3737551/153716172-724471a6-56c0-45bb-b053-f4a0c65112ef.png">

**Comment by MutsiMutsi** [comment]
Were you able to resolve this issue?

**Comment by andywenk** [comment]
I have the same - I used an older 0.3. version. With the Apple M1 Pro chip it runs. I assume some libraries in the newest version of surge are not working with Intel Chips. 

Because of: https://github.com/rule110-io/surge/blob/development/package.sh#L68
you may want to build it on your machine instead of downloading the .dmg . I will try it when I find a timeslot and give feedback here

**Comment by MutsiMutsi** [comment]
Thanks! @andywenk we're also aiming for a new release fairly soon due to congestion on the chain we cant always get away with 0 fee transactions for our pubsub transactions. More wallet features will be added to ensure longevity and usability during more congested times.

**Comment by MutsiMutsi** [comment]
We've realsed a new verison with builds for both mac architechtures, if your issue persists please let us know for now this ticket will be closed.
