### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by andywenk** [rule110-io/surge#93]
Hey,

first of all thank you for creating this. I really appreciate your work in your freetime. 

I got to surge via wallis, as surge is a example project. Cool. Unfortunately, I am not able to get it working with two peers. One is on Mac Book 1 and the other on Mac Book 2. I uploaded some example files, saw that there is a hash for them (for sure) and now ... I don't know how to proceed. 

* is there more docu than in the FAQ?
* can you maybe expalin simply how it works? I would be more than happy to test and share what I found

Thanks and all the best

Andy

**Comment by MutsiMutsi** [comment]
I think you got pretty far into it already, the general idea is that you create a channel to which you seed files. Those channels are decentralised pubsub topics (facilitated through nkn blockchain) when another client subscribes to that same topic, two way communication should allow for remote files to be shown and downloaded.

It is possible however at the time that the network (nkn) was congested and free (0 fee) transactions did not come through fast enough for the application to be usable. For those kinds of times we are integrating more wallet features so that this can be avoided with minimal cost (currently if fees are needed at all youre looking at fees at orders of magnitude lower than a dollarcent).

**Comment by andywenk** [comment]
Thanks very much @MutsiMutsi - I hope there will be more user soon.
